FROM base/java:8
VOLUME /tmp
ADD yourjar.jar app.jar

EXPOSE 11005

ENV JAVA_OPTS="-server -Xmx1g -Xms1g" agent_servicename="default"

ENTRYPOINT java -javaagent:/usr/local/skyagent/skywalking-agent.jar=agent.service_name=${agent_servicename} ${JAVA_OPTS} -jar /app.jar
