FROM hb.zjs.com.cn/zjsbaseimage/java:8-jdk-alpine-asla-shanghai-1-skyagent-2
VOLUME /tmp
ADD springcloud-zjs-example-mongodb-0.0.1.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 11005
ENTRYPOINT ["java","-javaagent:/usr/local/skyagent/skywalking-agent.jar=agent.service_name=mongodbdockertest","-jar","/app.jar"]
